version: '3.8'

services:
  backend:
    build: 
      context: server
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
  frontend:
    build: 
      context: client
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
  db:
    image: postgres:14.1-alpine
    restart: always
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db: