version: '3.8'

services:
  client:
    build: 
      context: client
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
  server:
    build: 
      context: server
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
  sqlite3:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - ./db/:/root/db/
volumes:
  db: